"""Seed lemma-link files from pre-existing @corresp evidence.

- ``sprengel1829 -> sprengel1829``: walk Sprengel chapter divs, pair them by
  @n into Greek↔Latin lemma-link records (Sprengel's own bilingual layout).
- ``berendes1902 -> berendes1902``: walk Berendes chapter heads, pair Greek
  and German @corresp lemma annotations.
"""
from __future__ import annotations

from datetime import datetime, timezone

from lxml import etree

from pharmacopoeia.lemmas.slugs import slugify as _slugify
from pharmacopoeia.paths import edition_tei, lemma_link_file

TEI_NS = "http://www.tei-c.org/ns/1.0"
XML_NS = "http://www.w3.org/XML/1998/namespace"
TEI = f"{{{TEI_NS}}}"
XID = f"{{{XML_NS}}}id"
XLANG = f"{{{XML_NS}}}lang"


def _emit_link_file(
    from_ns: str, to_ns: str, link_type: str,
    resp: str, cert: str, pairs: list[dict],
) -> None:
    tei = etree.Element(TEI + "TEI", nsmap={None: TEI_NS})
    header = etree.SubElement(tei, TEI + "teiHeader")
    fd = etree.SubElement(header, TEI + "fileDesc")
    ts = etree.SubElement(fd, TEI + "titleStmt")
    title = etree.SubElement(ts, TEI + "title")
    title.text = f"Lemma links: {from_ns} -> {to_ns}"
    ps = etree.SubElement(fd, TEI + "publicationStmt")
    p = etree.SubElement(ps, TEI + "p")
    p.text = (
        f"Generated by pharmacopoeia lemmas seed-links on "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}."
    )
    sd = etree.SubElement(fd, TEI + "sourceDesc")
    p2 = etree.SubElement(sd, TEI + "p")
    p2.text = (
        "Seeded mechanically from chapter @corresp pairs in the source TEI. "
        "Each link records the responsible party and evidence basis as a "
        "scholarly claim, not as a silent equivalence."
    )

    text = etree.SubElement(tei, TEI + "text")
    body = etree.SubElement(text, TEI + "body")
    linkgrp = etree.SubElement(body, TEI + "linkGrp")
    linkgrp.set("type", link_type)
    linkgrp.set("from", from_ns)
    linkgrp.set("to", to_ns)

    for i, pair in enumerate(pairs, start=1):
        link = etree.SubElement(linkgrp, TEI + "link")
        link.set(XID, f"link-{i:04d}")
        link.set("target", f"{pair['from']} {pair['to']}")
        link.set("cert", pair.get("cert", cert))
        link.set("resp", pair.get("resp", resp))
        link.set("evidence", pair.get("evidence",
                                       "edition source TEI @corresp pair"))
        if pair.get("note"):
            note = etree.SubElement(link, TEI + "note")
            note.text = pair["note"]

    etree.indent(tei, space="  ")
    out = lemma_link_file(from_ns, to_ns)
    out.parent.mkdir(parents=True, exist_ok=True)
    etree.ElementTree(tei).write(
        str(out), pretty_print=True, xml_declaration=True, encoding="utf-8",
    )
    print(f"lemma-links {from_ns}--{to_ns}: {len(pairs)} pairs -> {out}")


def _sprengel_grc_la_pairs() -> list[dict]:
    src = edition_tei("sprengel1829")
    tree = etree.parse(str(src))
    root = tree.getroot()

    by_n: dict[str, dict[str, dict]] = {}
    for ch in root.xpath(".//*[local-name()='div' and @subtype='chapter']"):
        n = ch.get("n")
        lang = ch.get(XLANG)
        head = ch.find(TEI + "head")
        if not n or not lang or head is None:
            continue
        text = "".join(head.itertext()).strip()
        head_form = text
        if lang == "grc":
            head_form = (head_form.removeprefix("Περὶ ")
                                 .removeprefix("Περί ").strip())
        elif lang == "la":
            head_form = head_form.removeprefix("De ").strip()
        slug = _slugify(head_form)
        lemma_id = f"lemma:sprengel1829-{lang}:{slug}"
        by_n.setdefault(n, {})[lang] = {"id": lemma_id, "text": text}

    pairs: list[dict] = []
    def _key(s: str) -> tuple:
        return tuple(int(x) for x in s.split(".") if x.isdigit())
    for n in sorted(by_n.keys(), key=_key):
        grc = by_n[n].get("grc")
        la = by_n[n].get("la")
        if not (grc and la):
            continue
        pairs.append({
            "from": grc["id"], "to": la["id"],
            "cert": "high", "resp": "#sprengel_himself",
            "evidence": (
                f"Sprengel's parallel Greek/Latin printing pairs chapter {n} "
                f"({grc['text']}) with ({la['text']})."
            ),
        })
    return pairs


def _berendes_grc_de_pairs() -> list[dict]:
    src = edition_tei("berendes1902")
    tree = etree.parse(str(src))
    root = tree.getroot()

    pairs: list[dict] = []
    for ch in root.xpath(".//*[local-name()='div' and @subtype='chapter']"):
        n = ch.get("n")
        head = ch.find(TEI + "head")
        if head is None:
            continue
        grc_id = grc_text = de_id = de_text = None
        for child in head.iter():
            corresp = child.get("corresp")
            if not corresp or not corresp.startswith("lemma:"):
                continue
            text = "".join(child.itertext()).strip()
            if corresp.startswith("lemma:berendes1902-grc:"):
                grc_id, grc_text = corresp, text
            elif corresp.startswith("lemma:berendes1902-de:"):
                de_id, de_text = corresp, text
        if grc_id and de_id:
            pairs.append({
                "from": grc_id, "to": de_id,
                "cert": "high", "resp": "#berendes_himself",
                "evidence": (
                    f"Berendes' chapter {n} head explicitly translates "
                    f"{grc_text} as {de_text}."
                ),
            })
    return pairs


def run(from_edition: str, to_edition: str) -> None:
    key = (from_edition, to_edition)
    if key == ("sprengel1829", "sprengel1829"):
        _emit_link_file(
            "lemma:sprengel1829-grc", "lemma:sprengel1829-la",
            link_type="lemma-translation",
            resp="#sprengel_himself", cert="high",
            pairs=_sprengel_grc_la_pairs(),
        )
        return
    if key == ("berendes1902", "berendes1902"):
        _emit_link_file(
            "lemma:berendes1902-grc", "lemma:berendes1902-de",
            link_type="lemma-translation",
            resp="#berendes_himself", cert="high",
            pairs=_berendes_grc_de_pairs(),
        )
        return
    raise NotImplementedError(
        f"seed-links not implemented for {from_edition} -> {to_edition}"
    )
